project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1 (Geospatial Data Wrangling with R)
            href: Hands-on_Ex1/Hands-on_Ex1.qmd
          - text: Hands-on Exercise 1 (Choropleth Mapping with R)
            href: Hands-on_Ex1/Hands-on_Ex1(cloreth).qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex2/Hands-on_Ex2.qmd
          - text: Hands-on Exercise 3
            href: Hands-on_Ex3/Hands-on_Ex3.qmd
          - text: Hands-on Exercise 4
            href: Hands-on_Ex4/Hands-on_Ex4.qmd
      - text: In-Class Exercises
        menu: 
          - text: In-Class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_ex1.qmd
          - text: In-Class Exercise 2
            href: In-class_Ex/In-class_Ex2/In-class_ex2.qmd
          - text: In-Class Exercise 3
            href: Hands-on_Ex3/Hands-on_Ex3.qmd
          - text: In-Class Exercise 4
            href: In-class_Ex/In-class_Ex4/In-class_ex4.qmd
      - text: Take Home Exercises
        menu: 
          - text: Take Home Exercise 1(Why Nigeria has so many broken waterpoints?)
            href: In-class_Ex/In-class_Ex2/In-class_ex2.qmd
          - text: Take Home Exercise 2
            href: Take-Home_Ex/Take-Home_Ex2/Take-Home_Ex2.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Darkly
    css: styles.css
    toc: true

editor: visual

