project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1 (Geospatial Data Wrangling with R)
            href: Hands-on_Ex1/Hands-on_Ex1.qmd
          - text: Hands-on Exercise 1 (Choropleth Mapping with R)
            href: Hands-on_Ex1/Hands-on_Ex1(cloreth).qmd
      - text: In-Class Exercises
        menu: 
          - text: In-Class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_ex1.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

